apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongo
    app: uniqloud
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017


---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo-service
    app: uniqloud
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
    app: uniqloud
